-   id: swift_lintfix
    name: Swift LintFix
    description: run swift lint, lint-fix, and format.
    entry: ENABLE_LINT_FIX=1 /usr/bin/swift package plugin --allow-writing-to-package-directory lintfix
    language: script
    files: '.*\.swift$'
